[target.x86_64-apple-darwin]
rustflags = [
    "-C", "target-feature=-avx,-avx2",
    "-C", "link-arg=-fuse-ld=lld"
]

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "target-cpu=native",
    "-C", "link-arg=-fuse-ld=lld"
]
