[package]
name = "grpc_service"
version = "0.1.0"
edition = "2024"

[[bin]]
name="server"
path="./src/bin/run_server.rs"

[[bin]]
name="client"
path="./src/bin/run_client.rs"

[dependencies]
anyhow = "1.0.97"
async-stream = "0.3.6"
prost = "0.13.5"
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
tokio-stream = "0.1.17"
tonic = { version = "0.13.0" }
tonic-health = "0.13.0"
uuid = { version = "1.16.0", features=["v4"] }

[build-dependencies]
tonic-build = "0.13.0"
