name: cargo checks
# TODO: change behaviour for checks vs formatting?
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  cargo-test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install protoc 
        uses: arduino/setup-protoc@v3

      - name: Compile
        run: cargo test --no-run --locked

      - name: Test
        run: cargo test -- --nocapture --quiet
