name: cargo test
# TODO: change behaviour for checks vs formatting?
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    env: 
      APP_DB__PASSWORD: postgres # override local.yaml
    services:
      test-db:
        image: postgres:latest
        env: 
          POSTGRES_PASSWORD: postgres # needed by postgres docker image
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Install protoc 
        uses: arduino/setup-protoc@v3
      - name: Compile
        run: cargo test --no-run --locked
      - name: Test
        run: cargo test -- --nocapture --quiet

  style:
    name: rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: 
            - rustfmt,clippy
      - name: Install protoc 
        uses: arduino/setup-protoc@v3
      - run: cargo fmt --check
      - run: cargo clippy -- -D warnings
